### PR TITLE
Convert to CMake based project

### PR DESCRIPTION
**Pull request by knro**
Thanks for the great library! I'm using this in my project and thought it would be great if it is CMake based instead of using the older Makefile. I tested this now with my project (using the cmake_modules/FindJetsonGPIO.cmake) and it works great!

A project could use it like this:

```
find_package(JetsonGPIO REQUIRED)
find_package(Threads REQUIRED)
include_directories(${JetsonGPIO_INCLUDE_DIR})
....
target_link_libraries(foo ${JetsonGPIO_LIBRARIES} Threads::Threads)
```

### CODE REVIEW

**Comment by pjueon** [comment]
First of all, thank you for the suggestion. I'll check and let you know.

**Comment by pjueon** [comment]
about 6c70009 

I checked the official python library (https://github.com/NVIDIA/jetson-gpio)
but I can't find any information about this.

in the official python library (lib/python/Jetson/GPIO/gpio_pin_data.py, line 85)
`({ 40:  20,  30:  16}, { 30: 'PCC.04'}, "c2f0000.gpio", 15, 22, 'GPIO12', 'TOUCH_CLK', None, None)`

Is this pin definition really true?

**Comment by knro** [comment]
Yes, this was actually verified on an actual NX board and the PWM was confirmed to work on PIN 15 once configured.

**Comment by pjueon** [comment]
Hmm... 

As you know, this project is a C++ port of the NVIDIA's official Python library.
So I want this library to work with the same logic as the Python library as much as possible.
(Of course, it hasn't fully reflected the latest version of the Python library yet though...)

I think it might be a good idea to apply this fix(6c70009) later when the Python library updates it.
(Maybe you can create a pull request directly to the official repository.)

**Comment by pjueon** [comment]
Okay, let's focus only on the CMake stuff in this pull request like its title.

First of all, I'm not familiar with CMake at all. So please forgive my ignorance.

1. About private headers.
The header files in the private folder shouldn't be copied when you install the libraray.
They should be "private", only used when you build the library.
Can you fix this please?

**Comment by knro** [comment]
Sure, it's done: https://github.com/NVIDIA/jetson-gpio/pull/63

**Comment by pjueon** [comment]
2. About header file install directory.
When I build and install the library by `sudo make isntall`,
JetsonGPIO.h file is copied to /usr/include/JetsonGPIO/

So I think,

when you build your own program using JetsonGPIO,
you should use `#include <JetsonGPIO/JetsonGPIO.h>` instead of `#include <JetsonGPIO.h>`
without any additional configuration.

Is my understanding right?

**Comment by knro** [comment]
No, it should be just `#include <JetsonGPIO.h>`

Notice that in the CMakeLists.txt, we already include it:

`include_directories(${JetsonGPIO_INCLUDE_DIR})`

Which includes /usr/include/JetsonGPIO files in the project.

**Comment by pjueon** [comment]
Oh, you mean when you compile your code using CMake?

But if you just compile your code without CMake or Makefile like the example in the README.md,
`g++ -o your_program_name your_source_code.cpp -lpthread -lJetsonGPIO`

the compiler will not be able to find JetsonGPIO.h file, right?

**Comment by knro** [comment]
You need to add -I/usr/include/JetsonGPIO to that and it would work. At any rate, CMake should probably be used since it makes using this much easier than a raw Makefile and also cross-platform friendly.

**Comment by pjueon** [comment]
Is there any reason that the header should be installed `/usr/include/JetsonGPIO` instead of `/usr/include/` ?
(any advantage/disadvantage, or conventional reason?)

If the install directory should be `/usr/include/JetsonGPIO` and you should use CMake to build your program,
I think we should edit the README.md (compiling user's code example part).


And could you tell me the reason why you changed the install directory prefix `/usr/local` to `/usr/` ?
Personally, I used `/usr/local` for no specific reason. I really don't know the differences between `/usr/local` and `/usr/`.
So I wonder why you changed it.

**Comment by knro** [comment]
For a single file, /usr/include makes more sense. However, in the C++ projects I manage, I always use a prefix. It's more tidy and you never know if you will add more include files in the future. The README should be updated.

Regarding /usr vs /usr/local, I prefer the format since it's installed to the system directory. From experience, you might end up with copies in both in /usr/local and in /usr and then a program fails to compile due to a conflict between the two. It's nice to establish clearly to install to /usr directory to avoid this confusion in the future.

**Comment by pjueon** [comment]
Thank you for the explanation.
If we use a prefix to the include directory, could you please update the compilation guide part of the README.md file?
(ex> how to compile with/without CMake, where will the header file be after installation, etc)


And using `/usr` instead of `/usr/local` sounds good to me. But there is one thing I'm worried about.
You said `you might end up with copies in both in /usr/local and in /usr and then a program fails to compile due to a conflict between the two.`

We are using `/usr/local` as the install directory right now. 
So if we update the install directory to `/usr`, 
Thoese who already installed previous version in `/usr/local` and re-install it after update might fail to compile due to the conflict.

Do you think we should update the install script to automatically uninstall previous version in /usr/local?
Or just adding a warnning to README.md file should be enough? What do you think?

**Comment by pjueon** [comment]
3. Questions about the version configuration in CMakeList.txt file. (probably very stupid questions, sorry)

I found the following lines in CMakeList.txt file
```
SET(LIBRARY_VERSION "1.0.0")
SET(LIBRARY_SOVERSION "1")
```

- Is the LIBRARY_VERSION supposed to be same as `GPIO::VERSION`(it's 1.0.3 right now) in JetsonGPIO.h? 
  And we should update LIBRARY_VERSION whenever `GPIO::VERSION` is changed, is my understanding right?

- What is LIBRARY_SOVERSION? Is it the first number of the LIBRARY_VERSION?
- After the installation, I found 3 .so files (`libJetsonGPIO.so`, `libJetsonGPIO.so.1.0.0` and `libJetsonGPIO.so.1`) 
  What is the difference among them? And how we should use them?

**Comment by knro** [comment]
Ok, I didn't know about 1.0.3, we can change to this now. The 3 libraries are correct, this is how libraries are installed on Linux. They're just symbolic links to the so.1.0.0. 

I don't think we should uninstalling anything. We can change the documentation so that we don't explicitly specify /usr and let used decide what to do with the CMake depending on their environment.

**Comment by pjueon** [comment]
Ok, I updated the version info and installation part of README. 
Could you please update the part about how to compile user's code?

**Comment by pjueon** [comment]
Thank you very much your contribute!

**Pull request merged**
